### PR TITLE
Mearge to main branch for task part 3

### PR DESCRIPTION
**Pull request by yhc59go**
Hi Peng Peng,

Here is the link for testing:
http://54.150.212.206:3000/
http://54.150.212.206:3000/attraction/10

Many Thanks,
Christine

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Put attenstion on margins.
2. Layout of mobile version is broken. Image Image slider should extend to full width and keep no margin space with navigator bar in mobile version.
54 150 212 206_3000_attraction_2(Samsung Galaxy S8+)
54 150 212 206_3000_attraction_2

**Comment by yhc59go** [comment]
I've revised the issues about layout. 
Thanks.

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Text in navigator bar breaks into 2 lines in 360px width devices.
2. Aspect ratio of any images in your page should keep the same as original ones.

**Comment by yhc59go** [comment]
I've revised the issues about layout.
Thanks.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
