### PR TITLE
Merge codes in develop branch to main branch for part 1

### PR DESCRIPTION
**Pull request by yhc59go**
Hi Peng Peng,

I would like to merge codes in develop branch to main branch for part 1-1.
Please review the commits.

Many Thanks,
Christine

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Paste your live URLs for testing and re-request review.

**Comment by yhc59go** [comment]
Hi Peng Peng,

These are the links for testing:
http://54.150.212.206:3000/api/categories
http://54.150.212.206:3000/api/attractions?page=0&keyword=藝文館所
http://54.150.212.206:3000/api/attractions?page=1
http://54.150.212.206:3000/api/attractions?page=0&keyword=北
http://54.150.212.206:3000/api/attraction/10

Many Thanks,
Christine

**Review by cwpeng — COMMENTED** [review]
Your live URLs are broken.

**Comment by yhc59go** [comment]
Hi Peng Peng,

I restarted the program and it is fine now.
(Ummm...I am not sure the root cause now.
I will keep track of it.)

Could you try again?

Many Thanks,
Christine

**Comment by yhc59go** [comment]
I modify the handel mechanism for exception.
Hope the links work well.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Result is OK but we should use `LIMIT` in SQL to do pagination than get ALL DATA and do it in your own code.

Solve this issue and re-request review.

**Comment by yhc59go** [comment]
I already revised by using LIMIT in SQL to do pagination than get ALL DATA. Thanks.

**Review by cwpeng — CHANGES_REQUESTED** [review]
You use `LIMIT` but it make no changes in the data processing flow.

It's expensive to `select id from attraction where category_id=%s`  and get attraction data one by one from database. It can be done ALL AT ONCE with `LIMIT` feature.

Try to investigate more and use it in a right way.

**Comment by yhc59go** [comment]
I already revised by integrating the SQL querys. Thanks.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
