### PR TITLE
Mearge to main branch for task part 2

### PR DESCRIPTION
**Pull request by yhc59go**
Hi Peng Peng,

Here is the link for testing:
http://54.150.212.206:3000

Many Thanks,
Christine

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Your layout exceeds screen width when screen width<1920px. There should not exist horizontal scroll bar in any situation.
2. Header and keyvisual section should extended to full width in mobile devices.
3. We should put category name into keyword input if we click one of them.

**Comment by yhc59go** [comment]
I revised the issues. 
Thanks!

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Testing in around 390px, layout exceed screen width.
2. Content in header, keyvisual and attraction list should align with each other to left or right in any devices larger than 1200px.
54 150 212 206_3000_(Pixel 5)

**Comment by yhc59go** [comment]
I revised the issues.
Thanks!

**Review by cwpeng — APPROVED** [review]
OK. Done.

But for middle size devices, ex. iPad, I think it's acceptable but not a good layout actually.

**Comment by yhc59go** [comment]
Thanks for your advice.
I will fine turning later.
Maybe....I think put 3 attractions in one row for middle size devices is more suitable.

**Pull request merged**
